workflows:
  expo-android-build:
    name: Expo Android Build
    max_build_duration: 60

    environment:
      node: 18

    scripts:
      - npm install
      - npx expo prebuild --platform android --clean
      - chmod +x android/gradlew

    working_directory: android

    scripts:
      - ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/**/*.apk
